CREATE TABLE IF NOT EXISTS arquivo (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome_original VARCHAR(100) NOT NULL,
    extensao VARCHAR(10) NOT NULL,
    data_upload TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);